// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGZbrS-EZbE3T8h82dgl3-kI9dRVGu4Ds',
    appId: '1:976623174181:web:813fda99e473102ad2b5cc',
    messagingSenderId: '976623174181',
    projectId: 'pillpilot10',
    authDomain: 'pillpilot10.firebaseapp.com',
    storageBucket: 'pillpilot10.appspot.com',
    measurementId: 'G-7930X9J803',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9ypCejWFhwhCycxuJKy5vdHEt6BopxSY',
    appId: '1:976623174181:android:74764b0799df96b1d2b5cc',
    messagingSenderId: '976623174181',
    projectId: 'pillpilot10',
    storageBucket: 'pillpilot10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1r3uWAHNP1hQwQvwTyMk_CS2gUpV2OTc',
    appId: '1:976623174181:ios:cc5416839f5fb32bd2b5cc',
    messagingSenderId: '976623174181',
    projectId: 'pillpilot10',
    storageBucket: 'pillpilot10.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1r3uWAHNP1hQwQvwTyMk_CS2gUpV2OTc',
    appId: '1:976623174181:ios:770dd5abac3ed151d2b5cc',
    messagingSenderId: '976623174181',
    projectId: 'pillpilot10',
    storageBucket: 'pillpilot10.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
